[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
# Server Configuration
PORT = "8000"
HOST = "0.0.0.0"
ENVIRONMENT = "production"
DEBUG = "false"

# CORS Configuration - Allow iOS app requests
ALLOWED_ORIGINS = "https://runbeat.app,https://api.runbeat.app,*"

# Firebase Configuration
# Note: Set these in Railway dashboard for security
# FIREBASE_API_KEY = "your-firebase-api-key"
# FIREBASE_PROJECT_ID = "runbeat-64b83"
# FIREBASE_STORAGE_BUCKET = "runbeat-64b83.firebasestorage.app"
# FIREBASE_SENDER_ID = "351570203287"

# Spotify Configuration  
# Note: Set these in Railway dashboard for security
# SPOTIFY_CLIENT_ID = "your-spotify-client-id"
# SPOTIFY_CLIENT_SECRET = "your-spotify-client-secret"

# Security
# SECRET_KEY = "your-secure-secret-key"

# Optional configurations
LOG_LEVEL = "INFO"
LOG_FORMAT = "json"
RATE_LIMIT_REQUESTS = "1000"
RATE_LIMIT_WINDOW = "60"
HEALTH_CHECK_TIMEOUT = "10"